### ISSUE TITLE
Create flashcard seed data

### ISSUE THREAD

**Issue by mbuotidem** [mbuotidem/FlashCards#6]
Words/Concepts and Definitions 

C# (20 items)

Data structures (20 items)

**Comment by mbuotidem** [comment]
@kaleab81 is this completed?

**Comment by kaleab81** [comment]
yes

**Comment by mbuotidem** [comment]
@Merxie-00  Kaleab created some seed data. Can you go through it and see if it meets the requirements above. I looked at it a while ago and it seemed to contain questions and four answers. Can you remove the incorrect answers since we only need a term and a definition? Thanks

**Comment by Merxie-00** [comment]
Data structure questions

1.	How can we describe an array in the best possible way?
•	Container that stores the elements of similar types
2.	Which of the following is the correct way of declaring an array?
•	int javatpoint[10];
3.	How do we initialize an array in C language?
•	int arr[2] = {10, 20}
4.	 Which of the following is the advantage of the array data structure?
•	Easier to access the elements in an array
5.	 Which of the following highly uses the concept of an array?
•	Spatial locality
6.	 Which of the following is the disadvantage of the array?
•	Wastage of memory if the elements inserted in an array are lesser than the allocated size
7.	 Which one of the following is the process of inserting an element in the stack?
•	Push
8.	 If the size of the stack is 10 and we try to add the 11th element in the stack then the condition is known as___
•	Overflow
9.	 Which one of the following is not the application of the stack data structure..
•	Asynchronous data transfer
10.	Which data structure is mainly used for implementing the recursive algorithm?
•	Stack
11.	 Which of the following is not the correct statement for a stack data structure?
•	Stack follows FIFO
12.	What is another name for the circular queue among the following options?
•	Ring buffer
13.	 Which principle does Queue use?
•	FIFO principle
14.	Which one of the following is not the application of the Queue data structure?
•	Balancing of symbols
15.	 The necessary condition to be checked before deletion from the Queue is__
•	Underflow
16.	Which data structure is the best for implementing a priority queue?
•	Heap
17.	A linear data structure in which insertion and deletion operations can be performed from both the ends is___
•	Deque
18.	 In the Deque implementation using singly linked list, what would be the time complexity of deleting an element from the rear end?
•	    O(n)
19.	 What is the maximum number of children that a node can have in a binary tree?
•	2

**Comment by Merxie-00** [comment]
I'm gonna edit some questions and put new ones .
