### ISSUE TITLE
Create "Choose a card deck" component

### ISSUE THREAD

**Issue by mbuotidem** [mbuotidem/FlashCards#7]
Based on output of #1

**Comment by mbuotidem** [comment]
@Merxie-00 could you share a screenshot of your flashcard component in its current state?

**Comment by Merxie-00** [comment]
![2021-04-07 (2)](https://user-images.githubusercontent.com/69064798/113901307-57dd3180-9794-11eb-8f19-7100e8f3d2bb.png)

**Comment by mbuotidem** [comment]
Thanks! Good work so far. Here are my thoughts. Looks good for an initial stab. As next steps:
 
- Rename your component to ChooseCardDeck.razor
- Create a list of deck objects in your @code block and loop through it in the html/razor section to display the deck names
- Create a page called DeckDetails that will display all the cards in the deck
- Include routing in your ChooseCardDeck.razor component such that when a user clicks on a deck name, they are taken to the DeckDetails page

**Comment by Merxie-00** [comment]
This is complete

**Comment by mbuotidem** [comment]
fixed by #15
