### ISSUE TITLE
Create flashcard component

### ISSUE THREAD

**Issue by mbuotidem** [mbuotidem/FlashCards#8]
Based on output from #2

**Comment by mbuotidem** [comment]
@Sarah94-mwema could you share a screenshot of your flashcard component in its current state?

**Comment by Sarah94-mwema** [comment]
![image](https://user-images.githubusercontent.com/78562730/113937684-27f75380-97bf-11eb-9f66-6e41ebdf14e0.png)

**Comment by Sarah94-mwema** [comment]
still in progress , i am working on flipping it , i am going to use the dummy objects until i am done working on the component

**Comment by mbuotidem** [comment]
fixed by #16
